# Generated by Django 5.2.4 on 2026-09-15 20:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image_product_is_best_seller_product_is_deal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='store_order_status_536f03_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'created_at'], name='store_order_user_id_1fd99b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='store_order_created_4ba192_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='store_order_order_i_70b6d9_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product'], name='store_order_product_056298_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['active', 'category'], name='store_produ_active_bf5c2c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['active', 'featured'], name='store_produ_active_d7c842_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['active', 'is_deal'], name='store_produ_active_5bfff9_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['active', 'is_flash_sale'], name='store_produ_active_4df734_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['active', 'is_best_seller'], name='store_produ_active_7c0716_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['active', 'is_new_arrival'], name='store_produ_active_2295f1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='store_produ_created_5555f3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='store_produ_price_2d55a6_idx'),
        ),
    ]
