# Generated by Django 5.2.4 on 2026-09-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_updated_at_alter_category_icon_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='store_order_created_4ba192_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='store_order_order_i_70b6d9_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='store_order_product_056298_idx',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
